os:
  - osx

language:
  - generic

addons:
  homebrew:
    update: true
    taps:
      - bazelbuild/tap
    casks:
      - java8
    packages:
      - bazel
      - python
      - python@2

script:
  - bazel test ...
