os:
  - osx

language:
  - java

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

addons:
  homebrew:
    update: true
    taps:
      - bazelbuild/tap
    packages:
      - bazel
      - python
      - python@2

script:
  - bazel test ...
